### ISSUE TITLE
KubeFATE support liveness and readiness

### ISSUE THREAD

**Issue by owlet42** [FederatedAI/KubeFATE#552]
**Summary**

Supporting liveness and readiness can better display the status of the cluster and increase the high availability of the cluster.

**Subtask**

- [ ] docker-compose(Dockerfile) support healthcheck.
- [ ] charts support liveness and readiness.
- [ ] kubefate server support liveness and readiness.
